title: My experiences
author: Hadi
email: hadi@email.ca
description: > # this means to ignore newlines until "baseurl:"
  Place where I share my experinces in my daily life.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
